### ISSUE TITLE
foo_lnk to follow folder.lnks

### ISSUE THREAD

**Issue by blausand** [stengerh/foo_multiformat#1]
(Da ich den Code für Dein foo_lnk hier nicht finden kann, missbrauche ich mal foo_multiformat für die Kontaktaufnahme.)

Hallo Holger!
Ich hab mir zur Angewohnheit gemacht, wenn ich von jemensch Musik bekomme, diese (zunächst sauber zu taggen und dann), bevor ich sie in meine Genre-Überordner verstaue, alle neu bekommenen Ordner zu markieren und mit einem Handstreich Verknüpfungen zu erstellen, die in einem speziellen Ordner für Herkunftsnachweise verbleiben. In dem sind also lauter Ordner mit den Namen "[von $freundIn]" etc.
Damit weiß ich von wem, aber auch vor allem, WANN ich etwas bekommen habe.
Gegenüber genuinen Playlists hat das den Vorteil, dass Windows Verknüpfungen heilt, wenn man das Ziel verschiebt, was ich ja IMMER beim Einsortieren tue. 

Nun kann ich foobar2000 zwar diese Ordner in eine Playlist schieben, diese aufzulösen schlägt allerdings fehl - sogar, mit Deinem PlugIn.
![lala-herkunftsnachweise-als-folder-lnks](https://cloud.githubusercontent.com/assets/1245050/18193725/a29a974c-70e0-11e6-8d2b-4d0f406977ae.png)

Frage: Wäre es ein großer Akt, auch Verknüpfungen, die auf Ordner verweisen, aufzulösen?
Danke für die Antwort und ggf. für den Code hier auf github!

**Comment by stengerh** [comment]
Das wird leider nicht möglich sein. Der Mechanimus, über den sich foo_lnk enklinkt ([link_resolver](http://foosion.foobar2000.org/doxygen/latest/classlink__resolver.html)), erlaubt nur Audiodateien als Ziele.

Ich habe ein Platzhalter-Repo erstellt und mir eine Notiz (stengerh/foo_lnk#1) gemacht, den Code hochzuladen. Leider habe habe ich ihn auf meinem aktuellen Rechner nicht drauf, sonst hätte ich das gleich gemacht. ;)
